### ISSUE TITLE
Spark DB

### ISSUE THREAD

**Issue by mikeumus** [Bus-Data-NYC/oba-path-extractor#1]
Hey @nathan9 & @kuanb, I remember when we worked together at BetaNYC that one night and you guys were trying to figure out how to get fast queries on a large dataset. I started taking an edX class on [Scalable Machine Learning](https://courses.edx.org/courses/BerkeleyX/CS190.1x/1T2015/) and they're describing [Apache Spark](http://spark.apache.org/) database as a solution for this, check it out here:
- https://www.youtube.com/watch?v=vat5Jki1lbI

**Comment by nathan9** [comment]
Thanks! We opted to use a traditional database for now and just
prepare/aggregate the data for a limited set of queries, but plan to
support ad hoc queries in the future. I'll definitely try using Spark for
that.

**Comment by mikeumus** [comment]
:+1:
